// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTpYTE2AoE-b27Rp7LH5gojMHsY-83rA4',
    appId: '1:243132921680:web:6d3e642f363ab363359e55',
    messagingSenderId: '243132921680',
    projectId: 'quiz-c9870',
    authDomain: 'quiz-c9870.firebaseapp.com',
    storageBucket: 'quiz-c9870.appspot.com',
    measurementId: 'G-Q9WBSMDZ2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEuGkh9BkuglTABQCmMxV7sOgtcqpZt_I',
    appId: '1:243132921680:android:e8afc077f5427955359e55',
    messagingSenderId: '243132921680',
    projectId: 'quiz-c9870',
    storageBucket: 'quiz-c9870.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBasRRXvRMcArNg7_yZyQXc5qtikpJaazo',
    appId: '1:243132921680:ios:908b2c68196642fb359e55',
    messagingSenderId: '243132921680',
    projectId: 'quiz-c9870',
    storageBucket: 'quiz-c9870.appspot.com',
    iosBundleId: 'com.example.quiz',
  );
}
